spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/upvoter?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true

logging:
    level:
        com.horsika: info
        org.springframework.web: info
        org.hibernate: error
        org.springframework.security: debug
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
